version: "3.5"
services:
    postgres:
        image: postgres:16
        container_name: velo-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            # Persistent data
            - ./db_data/postgres:/var/lib/postgresql/data
            # Optional init SQL scripts
            - ./velo/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql