"""Updated table schemas --all IDs to BigInteger

Revision ID: 7fec0abbf63c
Revises: 2e64f1f4f419
Create Date: 2025-10-13 16:24:26.140470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fec0abbf63c'
down_revision: Union[str, Sequence[str], None] = '2e64f1f4f419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
