"""Updated table schemas --pre integration & debug

Revision ID: b448a37705a3
Revises: 95bd5379f1aa
Create Date: 2025-10-11 21:24:53.790305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b448a37705a3'
down_revision: Union[str, Sequence[str], None] = '95bd5379f1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column('artifacts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('artifacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'artifacts', 'campaigns', ['campaign_id'], ['id'])
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'output_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'output_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('artifacts', 'updated_at')
    op.drop_column('artifacts', 'created_at')
    op.drop_column('artifacts', 'campaign_id')
    # ### end Alembic commands ###
